# Generated by Django 3.2.4 on 2021-06-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('apelido', models.CharField(max_length=30)),
                ('telefone', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=254)),
                ('dataNascimento', models.DateTimeField()),
            ],
        ),
    ]
