# Generated by Django 3.2.4 on 2021-06-27 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textoPergunta', models.CharField(max_length=200)),
                ('pontos', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Quizz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituloPergunta', models.CharField(max_length=50)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('due', models.DateField()),
                ('tentativas', models.PositiveIntegerField()),
                ('tempo', models.PositiveIntegerField()),
                ('perguntas', models.ManyToManyField(to='quizz.Pergunta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textoResposta', models.CharField(max_length=50)),
                ('correta', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tentativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizz.pergunta')),
                ('quizz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizz.quizz')),
                ('resposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizz.resposta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pergunta',
            name='respostas',
            field=models.ManyToManyField(to='quizz.Resposta'),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
