# Generated by Django 3.2.4 on 2021-07-04 16:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tentativa',
            name='classificacao',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tentativa',
            name='submetido',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
